# Generated by Django 5.1.1 on 2024-10-04 16:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_B_test', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelassignment',
            name='recommendations_model',
            field=models.CharField(choices=[('A', 'Modello A'), ('B', 'Modello B'), ('C', 'Modello C')], editable=False, max_length=1),
        ),
        migrations.AlterField(
            model_name='modelassignment',
            name='user_id',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
