# Generated by Django 5.1.1 on 2024-10-04 16:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_B_test', '0002_alter_modelassignment_recommendations_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelassignment',
            name='recommendations_model',
            field=models.CharField(choices=[('A', 'Modello A'), ('B', 'Modello B')], editable=False, max_length=1),
        ),
        migrations.AlterField(
            model_name='modelassignment',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
