# Generated by Django 5.1.1 on 2024-10-05 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('A_B_test', '0004_rename_user_id_modelassignment_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modelassignment',
            options={'ordering': ['user']},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['id']},
        ),
    ]
